pipeline {
    agent any
    stages {
        stage('Build & Test') {
            steps {
                // Phải chui vào đây thì lệnh mvn mới chạy được
                dir('Jenkins_Demo_Project') {
                    echo '>>> Dang chui vao thu muc code...'
                    bat 'mvn clean test'
                }
            }
        }
    }
}
