pipeline {
    agent any
    
    stages {
        stage('Build & Test') {
            steps {
                echo '>>> Dang cai dat thu vien va chay Test...'
                // Chạy lệnh Maven trên Windows
                bat 'mvn clean test'
            }
        }
    }
    
    post {
        success {
            echo '>>> SUCCESS: Chuc mung! Code chay ngon.'
        }
        failure {
            echo '>>> FAILURE: Toang roi! Code co loi.'
        }
    }
}