pipeline {
    agent any
    stages {
        stage('Test Google') {
            steps {
                // Đây là "chìa khóa": Dẫn Jenkins vào thư mục chứa pom.xml
                dir('Jenkins_Demo_Project') {
                    echo '>>> Dang chui vao thu muc code de tim pom.xml...'
                    bat 'mvn clean test'
                }
            }
        }
    }
}
